@echo off
echo 🚀 IdeaSpark - Deployment Script
echo ================================
echo.

REM Check if Terraform has been applied
if not exist "terraform.tfstate" (
    echo ❌ Terraform state not found!
    echo    Please run: terraform init ^&^& terraform apply
    pause
    exit /b 1
)

echo 📊 Getting AWS credentials from Terraform...

REM Get outputs from Terraform
for /f "delims=" %%i in ('terraform output -raw aws_access_key_id 2^>nul') do set AWS_ACCESS_KEY=%%i
for /f "delims=" %%i in ('terraform output -raw aws_secret_access_key 2^>nul') do set AWS_SECRET_KEY=%%i
for /f "delims=" %%i in ('terraform output -raw amplify_app_id 2^>nul') do set AMPLIFY_APP_ID=%%i
for /f "delims=" %%i in ('terraform output -raw amplify_default_domain 2^>nul') do set APP_URL=%%i

if "%AWS_ACCESS_KEY%"=="" (
    echo ❌ Could not retrieve AWS credentials from Terraform
    pause
    exit /b 1
)

echo ✅ Retrieved AWS credentials

REM Update config.js
echo 🔧 Updating configuration...

(
echo // AWS Configuration
echo // Auto-generated by deploy.bat - DO NOT COMMIT THIS FILE
echo export const AWS_CONFIG = {
echo   region: 'us-east-1',
echo   credentials: {
echo     accessKeyId: '%AWS_ACCESS_KEY%',
echo     secretAccessKey: '%AWS_SECRET_KEY%'
echo   }
echo };
echo.
echo export const TABLES = {
echo   IDEAS: 'ideaspark-ideas',
echo   GROUPS: 'ideaspark-groups'
echo };
) > src\config.js

echo ✅ Configuration updated

REM Build the application
echo.
echo 📦 Building application...
call npm run build

if not exist "dist" (
    echo ❌ Build failed - dist directory not found
    pause
    exit /b 1
)

echo ✅ Build successful

echo.
echo 🚀 Deploying to AWS Amplify...
echo.
echo 📊 Amplify App ID: %AMPLIFY_APP_ID%
echo 🌐 App URL: %APP_URL%
echo.
echo ⚠️  Manual deployment required:
echo    1. Go to: https://console.aws.amazon.com/amplify/
echo    2. Select your app: %AMPLIFY_APP_ID%
echo    3. Click "Deploy without Git"
echo    4. Upload the 'dist' folder
echo.
echo    Or use AWS CLI to deploy automatically
echo.

echo ✅ Build complete!
echo.
echo 🌐 Your app will be available at:
echo    %APP_URL%
echo.
echo 📊 Monitor deployment in AWS Console:
echo    https://console.aws.amazon.com/amplify/
echo.
echo 🎉 Done!
pause
