#!/bin/bash
set -e

echo "🚀 IdeaSpark - Deployment Script"
echo "================================"
echo ""

# Check if Terraform has been applied
if [ ! -f "terraform.tfstate" ]; then
    echo "❌ Terraform state not found!"
    echo "   Please run: terraform init && terraform apply"
    exit 1
fi

echo "📊 Getting AWS credentials from Terraform..."

# Get AWS credentials from Terraform output
AWS_ACCESS_KEY=$(terraform output -raw aws_access_key_id 2>/dev/null)
AWS_SECRET_KEY=$(terraform output -raw aws_secret_access_key 2>/dev/null)
AWS_REGION=$(terraform output -json | grep -o '"aws_region"[^}]*' | grep -o '"value":"[^"]*' | cut -d'"' -f4)
AMPLIFY_APP_ID=$(terraform output -raw amplify_app_id 2>/dev/null)

if [ -z "$AWS_ACCESS_KEY" ] || [ -z "$AWS_SECRET_KEY" ]; then
    echo "❌ Could not retrieve AWS credentials from Terraform"
    exit 1
fi

echo "✅ Retrieved AWS credentials"

# Update config.js with actual credentials
echo "🔧 Updating configuration..."

cat > src/config.js << EOF
// AWS Configuration
// Auto-generated by deploy.sh - DO NOT COMMIT THIS FILE
export const AWS_CONFIG = {
  region: '${AWS_REGION:-us-east-1}',
  credentials: {
    accessKeyId: '$AWS_ACCESS_KEY',
    secretAccessKey: '$AWS_SECRET_KEY'
  }
};

export const TABLES = {
  IDEAS: 'ideaspark-ideas',
  GROUPS: 'ideaspark-groups'
};
EOF

echo "✅ Configuration updated"

# Build the application
echo ""
echo "📦 Building application..."
npm run build

if [ ! -d "dist" ]; then
    echo "❌ Build failed - dist directory not found"
    exit 1
fi

echo "✅ Build successful"

# Create deployment package
echo ""
echo "📦 Creating deployment package..."
cd dist
zip -r ../deployment.zip . > /dev/null
cd ..

echo "✅ Deployment package created"

# Deploy to Amplify
echo ""
echo "🚀 Deploying to AWS Amplify..."

if [ -z "$AMPLIFY_APP_ID" ]; then
    echo "❌ Amplify App ID not found"
    exit 1
fi

# Create a deployment using AWS CLI
aws amplify start-deployment \
    --app-id "$AMPLIFY_APP_ID" \
    --branch-name main \
    --source-url "deployment.zip" \
    2>/dev/null || {
        echo "⚠️  Direct deployment failed, using manual upload method..."
        
        # Alternative: Upload to S3 and deploy
        BUCKET_NAME="ideaspark-deploy-$(date +%s)"
        aws s3 mb "s3://$BUCKET_NAME" 2>/dev/null || true
        aws s3 cp deployment.zip "s3://$BUCKET_NAME/deployment.zip"
        
        echo "📦 Uploaded to S3: s3://$BUCKET_NAME/deployment.zip"
        echo "   Please deploy manually from Amplify Console"
    }

# Get the app URL
APP_URL=$(terraform output -raw amplify_default_domain 2>/dev/null)

echo ""
echo "✅ Deployment complete!"
echo ""
echo "🌐 Your app is available at:"
echo "   $APP_URL"
echo ""
echo "📊 Monitor deployment:"
echo "   https://console.aws.amazon.com/amplify/home?region=${AWS_REGION:-us-east-1}#/$AMPLIFY_APP_ID"
echo ""
echo "⚠️  Note: It may take 2-3 minutes for the deployment to complete"
echo ""

# Cleanup
rm -f deployment.zip

echo "🎉 Done!"
